# Generated by Django 5.2.8 on 2025-11-28 13:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("features", 4),
                            ("courses", 7),
                            ("registration", 10),
                            ("profiles", 13),
                            ("trusted_by", 16),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("icon", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.ListBlock", (3,), {}),
                            5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("excerpt", 1), ("link", 5)]],
                                {},
                            ),
                            7: ("wagtail.blocks.ListBlock", (6,), {}),
                            8: ("wagtail.blocks.CharBlock", (), {}),
                            9: ("wagtail.blocks.URLBlock", (), {}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 8), ("cta_text", 8), ("cta_link", 9)]],
                                {},
                            ),
                            11: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 8), ("role", 11), ("image", 2), ("bio", 1)]],
                                {},
                            ),
                            13: ("wagtail.blocks.ListBlock", (12,), {}),
                            14: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("logo", 14), ("name", 8)]],
                                {},
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                        },
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "link",
                    models.CharField(
                        help_text="Use absolute path (eg /about/) or full external URL",
                        max_length=500,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SiteHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=255)),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
        ),
    ]
