# Generated by Django 5.2.8 on 2025-11-28 14:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("features", 4),
                    ("courses", 10),
                    ("registration", 13),
                    ("profiles", 16),
                    ("trusted_by", 19),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("icon", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: ("wagtail.blocks.DateBlock", (), {"required": False}),
                    6: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "e.g., $49.99", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Number of reviews", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("excerpt", 1),
                                ("date", 5),
                                ("image", 2),
                                ("link", 6),
                                ("price", 7),
                                ("reviews_count", 8),
                            ]
                        ],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: ("wagtail.blocks.CharBlock", (), {}),
                    12: ("wagtail.blocks.URLBlock", (), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 11), ("cta_text", 11), ("cta_link", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 11), ("role", 14), ("image", 2), ("bio", 1)]],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("logo", 17), ("name", 11)]],
                        {},
                    ),
                    19: ("wagtail.blocks.ListBlock", (18,), {}),
                },
                null=True,
            ),
        ),
    ]
